feat(memento): #MVS-110 add check access memento
OPEN-ENT-NG/vie-scolaire pull request #103
Opened 2023-03-29 15:04 UTC by JinDouang

## Describe your changes

* Ajout de vérification côté API et côté client pour accéder au memento
* Vu avec l'équipe fonctionnelle pour dire qu'on doit être de profil **Personnel** ou **Enseignant** pour accéder aux APIs/clients memento
* Doc API : https://confluence.support-ent.fr/display/MTVS/Memento+API

## Checklist tests

En tant qu'enseignant/personnel : 

Aller sur présences -> accéder à la liste des événements -> cliquer un élève => On a accès au memento

les APIs : 

```
${host}/viescolaire/memento/access
${host}/viescolaire/memento/students/{:studentId}
```

Doivent retourner les infos et true pour l'endpoint `access`.

Les comptent n'ayant pas le profil personnel/enseignant doivent avoir une erreur 401

## Issue ticket number and link

https://jira.support-ent.fr/browse/MVS-110

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-03-29 15:10 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/security/memento/AccessMemento.java
> +        handler.handle((Field.TEACHER.equals(userInfos.getType()) || Field.PERSONNEL.equals(userInfos.getType())));
vu avec l'équipe fonctionnel pour dire qu'on accède au memento en ayant le profil "teacher" ou "personnel"

2023-03-29 15:10 UTC, JinDouang commented on src/main/resources/public/modules/viescolaire/ts/memento/memento.ts
> +            let mementoAccess: MementoAccess = await mementoService.checkAccess();
On rajoute le try / catch avec le service qui interroge angularJS pour voir si l'user a droit accès à memento pour continuer l'interaction

Elle est également protégé côté back avec `MementoAccess.class`.

2023-03-29 15:48 UTC, qpic-cgi requested changes

2023-03-29 15:48 UTC, qpic-cgi commented on src/main/java/fr/openent/viescolaire/controller/MementoController.java
> +                        renderJson(request, new JsonObject().put(Field.ACCESS, isAuthorized))));
pourquoi faire un endpoint, tu ne peux pas récupérer l'info directement en front ?

2023-03-29 15:59 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/controller/MementoController.java
> +                        renderJson(request, new JsonObject().put(Field.ACCESS, isAuthorized))));
Je pourrais mais j'ai fait le choix de le gérer côté back comme ça reprend la même logique

Ca peut aussi m'éviter de faire une repasse côté front (surtout qu'aujourd'hui, je t'avouerai je sais pas trop quel champ utiliser (jsuis mitigé sur les utilisations entre `Profiles ` , `functions ` et `type`

De plus, côté back y a des "exemples" sur les ResourcesFilter où ils font ce genre de vérification  donc j'en ai profité pour l'utiliser (comme celui-ci par ex: https://github.com/opendigitaleducation/entcore/blob/master/directory/src/main/java/org/entcore/directory/security/TeacherOfUser.java#L50)

2023-03-29 16:11 UTC, qpic-cgi commented on src/main/java/fr/openent/viescolaire/controller/MementoController.java
> +                        renderJson(request, new JsonObject().put(Field.ACCESS, isAuthorized))));
Okey ça marche !

2023-03-29 16:11 UTC, qpic-cgi approved these changes

2023-03-30 06:48 UTC, lapeyronnie approved these changes

2023-03-30 06:59 UTC, merged