feat(MA-1067): add API to check of teachers unattached to classes
OPEN-ENT-NG/vie-scolaire pull request #104
Opened 2023-03-31 16:28 UTC by flmartineau

## Describe your changes

- add new API for checking teachers with no classes
- add new API for checking the initialization status of a structure

Related to https://github.com/OPEN-ENT-NG/presences/pull/296

## Checklist tests

- check the API routes are behaving properly: a response is received if the user has the proper rights.

## Issue ticket number and link

https://jira.support-ent.fr/browse/MA-1067

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-04-03 06:21 UTC, Rseuret approved these changes

2023-04-03 08:38 UTC, BastienBenard reviewed
Est ce que tu peux faire des tests sur le nouveau service ?

2023-04-03 08:38 UTC, BastienBenard commented on src/main/java/fr/openent/viescolaire/controller/InitController.java
> +    @ResourceFilter(AdministratorRight.class)
doc d'api dans la description de la PR

2023-04-03 08:38 UTC, BastienBenard commented on src/main/java/fr/openent/viescolaire/controller/InitController.java
> +                            "teachers initialization status", this.getClass().getSimpleName()), fail);
fail => fail.getMessage() ?

2023-04-03 08:38 UTC, BastienBenard commented on src/main/java/fr/openent/viescolaire/model/InitTeachers.java
> +        this.teachers = json.getJsonArray(Field.TEACHERS).stream().map(o -> new User((JsonObject) o)).collect(Collectors.toList());
```suggestion
        this.teachers = json.getJsonArray(Field.TEACHERS).stream()
           .filter(JsonObject.class::isInstance)
           .map(JsonObject.class::cast)
           .map(User.class::new)
           .collect(Collectors.toList());
```

2023-04-03 08:38 UTC, BastienBenard commented on src/main/java/fr/openent/viescolaire/service/InitService.java
> +    Future<Boolean> getInitializationStatus(String structureId);
Possible une Java doc

2023-04-03 08:38 UTC, BastienBenard commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultInitService.java
> +                initTeachers.setTeachers(teachers.stream().map(o -> new User((JsonObject) o)).collect(Collectors.toList()));
```suggestion
                initTeachers.setTeachers(teachers.stream()
                .filter(JSonObject.class::isInstance)
                .map(JsonObject.class::cast)
                .map(User.class::new)
                .collect(Collectors.toList()));
```

2023-04-04 07:12 UTC, JinDouang requested changes

2023-04-04 07:12 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/controller/InitController.java
> +                            "initialization status", this.getClass().getSimpleName()), fail);
fail.getMessage() ?

2023-04-04 09:55 UTC, merged