feat(MA-1000): add initialization of default subject
OPEN-ENT-NG/vie-scolaire pull request #107
Opened 2023-04-05 15:46 UTC by flmartineau

## Describe your changes

- added initialization function for default subject
- added new optional configuration key `"initDefaultSubject": ${initDefaultSubject}`

## Checklist tests

- Check if the initialisation creates a new subject called "Ecole" or with the name specified in viescolaire configuration.

## Issue ticket number and link

https://jira.support-ent.fr/browse/MA-1000

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-04-05 15:49 UTC, flmartineau commented on src/main/java/fr/openent/viescolaire/helper/MessageResponseHandler.java
Fichier repris depuis Magnéto (https://github.com/OPEN-ENT-NG/magneto/blob/dev/src/main/java/fr/cgi/magneto/helper/MessageResponseHandler.java)

2023-04-05 15:50 UTC, flmartineau commented on src/main/java/fr/openent/viescolaire/worker/InitWorker1D.java
> +        this.initService.initSubjects(this.structureId, defaultSubjectLabel, "099999")
Le code de la matière par défaut est un code à 6 chiffres choisi arbitrairement.

2023-04-06 06:44 UTC, JinDouang requested changes

2023-04-06 06:44 UTC, JinDouang commented on deployment/viescolaire/conf.j2
> +        "initDefaultSubject": "ECOLE"
Est-ce qu'on ne pourrait pas mettre en place un enum ou autre pour avoir une "liste" des labels potentiels ?
est-ce qu'on peut aussi le mettre sous forme de i18n ?

2023-04-07 07:40 UTC, flmartineau commented on deployment/viescolaire/conf.j2
> +        "initDefaultSubject": "ECOLE"
Le label peut-être n'importe quoi. Ca correspond au nom de la matière par défaut. Si la clé n'existe pas il va récupérer une clé i18n.

2023-04-07 07:54 UTC, BastienBenard approved these changes

2023-04-19 12:42 UTC, merged