feat(init-1D): #MA-1001 add initialization of services
OPEN-ENT-NG/vie-scolaire pull request #108
Opened 2023-04-19 12:57 UTC by flmartineau

## Describe your changes

- add initialization of services for 1D from the neo4J teachers/classes

## Checklist tests

- check if the initialization of services generates services from the correct data
- check if service creation/update is still working properly

## Issue ticket number and link

https://jira.support-ent.fr/browse/MA-1001
https://jira.support-ent.fr/browse/MVS-117

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [x] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-04-19 13:23 UTC, flmartineau commented on src/main/java/fr/openent/viescolaire/helper/TransactionHelper.java
Code récupéré depuis CRRE : 

https://github.com/CGI-OPEN-ENT-NG/crre/blob/dev/src/main/java/fr/openent/crre/helpers/TransactionHelper.java

2023-04-19 13:24 UTC, flmartineau commented on src/main/java/fr/openent/viescolaire/model/TransactionElement.java
Codé récupéré de CRRE  :

https://github.com/CGI-OPEN-ENT-NG/crre/blob/dev/src/main/java/fr/openent/crre/model/TransactionElement.java

2023-04-20 08:02 UTC, Sofianebernoussi approved these changes

2023-04-20 08:02 UTC, Sofianebernoussi commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultInitService.java
> +                    ((List<JsonObject>) teachers.getList()).forEach(teacher -> {
pasm ieux de faire un stream etcc ? pour eviter les erreurs si jamasi tu recup autre chose qu'un json

2023-04-20 08:27 UTC, BastienBenard commented on src/main/java/fr/openent/viescolaire/worker/InitWorker1D.java
> +    @SuppressWarnings("unchecked")
Est ce que c'est réellement utiles ?

2023-04-20 09:33 UTC, FlorentMr approved these changes

2023-04-20 13:19 UTC, JinDouang requested changes

2023-04-20 13:19 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/model/InitServiceModel.java
> +    private Boolean is_visible;
Si possible, faire en camelCase (https://rules.sonarsource.com/java/tag/convention/RSPEC-117)

2023-04-20 13:19 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultInitService.java
> +                    });
Pour répondre à @Sofianebernoussi en mode stream, voici une proposition : 


```suggestion
     teachers.stream()
                            .filter(JsonObject.class::isInstance)
                            .map(JsonObject.class::cast)
                            .collect(Collectors.toList()).forEach(teacher -> {
                                String teacherId = teacher.getString(Field.ID);

                                List<String> classIds = teacher.getJsonArray(Field.CLASSIDS, new JsonArray())
                                        .stream()
                                        .filter(String.class::isInstance)
                                        .map(String.class::cast)
                                        .collect(Collectors.toList());
                              
                                List<String> groupIds = teacher.getJsonArray(Field.GROUPIDS, new JsonArray())
                                        .stream()
                                        .filter(String.class::isInstance)
                                        .map(String.class::cast)
                                        .collect(Collectors.toList());
                                classIds.addAll(groupIds);

                                if (!classIds.isEmpty()) {
                                    InitServiceModel service = new InitServiceModel(
                                            new JsonObject()
                                                    .put(Field.ID_MATIERE, subject.getId())
                                                    .put(Field.ID_GROUPES, classIds)
                                                    .put(Field.ID_ENSEIGNANT, teacherId)
                                                    .put(Field.ID_ETABLISSEMENT, structureId));

                                    createServiceFutures.add(this.servicesService.createService(service));
                                }    
                            
                            });
```

@BastienBenard @qpic-cgi

2023-04-20 13:19 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultInitService.java
> +                                promise.fail(fail);
Le 2eme param ne sera pas pris en compte dans les logs
je te suggère un rajout de %s avec le fail.getMessage()

```suggestion
  LOGGER.error(String.format("[Viescolaire@%s::initServices] Failed to create services: %s",
                                        this.getClass().getSimpleName(), fail.getMessage()));
                                promise.fail(fail.getMessage());
```

de plus, il vaut mieux faire un promise.fail en mettant la trace exception

2023-04-20 13:19 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/worker/InitWorker1D.java
> +    @SuppressWarnings("unchecked")
je suis d'accord, ca n'a pas l'air d'être utile (pas de warning)

2023-04-20 13:19 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/worker/InitWorker1D.java
> +                    this.mainSubject = new SubjectModel(res.getJsonArray(Field.RESULTS).getJsonArray(0).getJsonObject(0));
risque index inbound exception

2023-04-20 13:19 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/worker/InitWorker1D.java
>                      String message = String.format("[Viescolaire@%s::initSubjects] Failed to init subjects", this.getClass().getSimpleName());
arf dommage on ne l'a pas vu dans une de tes PRs mais faudrait revoir le format et l'envoie des logs (cf commentaire au-dessus)

2023-04-20 13:19 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/worker/InitWorker1D.java
> +                    String message = String.format("[Viescolaire@%s::initServices] Failed to init services", this.getClass().getSimpleName());
cf commentaire au-dessus

2023-04-21 07:49 UTC, merged