feat(grouping):#MVS-68 add front for grouping
OPEN-ENT-NG/vie-scolaire pull request #34
Opened 2022-07-27 15:54 UTC by vava56754

## Describe your changes
Création du front pour les groupings(regroupements). Les tests unitaires ne passent pas pour le moment en raison d'une simulation de requêtes réussis dans le service. Création de données pour pouvoir tester les fonctionnalités.
## Checklist tests
- [x] Création de grouping
- [x] Modification du nom du grouping
- [x] Suppression d'un grouping
- [x] Ajout de classe au grouping
- [x] Suppression de classe au grouping 
## Issue ticket number and link
MVS-68: https://entsupport.gdapublic.fr/browse/MVS-68
## Checklist before requesting a review (magic string, indentation, comment/documentation...)
Certaines lignes sont commentées et seront décommentées à l'avenir au moment du branchement avec le back.
- [x] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [x] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-07-28 07:12 UTC, BastienBenard commented on src/main/resources/i18n/fr.json
>    "viescolaire.connection.offline": "Votre appareil a perdu sa connexion à Internet",
Est ce que tu peux faire les i18n anglais stp ?

2022-07-28 07:19 UTC, BastienBenard commented on src/main/resources/public/modules/viescolaire/controllers/vsco_grouping_ctrl.ts
> +export const groupingController = ng.controller('groupingController', ['$scope', 'route', 'model', function ($scope, route) {
Tu peux utiliser les model de classes.

2022-07-28 07:27 UTC, qpic-cgi commented on src/main/resources/public/modules/viescolaire/controllers/vsco_grouping_ctrl.ts
> +    toto(): void;
ha oui tiens, c'est toujours utile une petite méthode "toto"

2022-07-28 07:27 UTC, qpic-cgi commented on src/main/resources/public/modules/viescolaire/controllers/vsco_grouping_ctrl.ts
> +    getGrouping(): any;
getGrouping(): any ?

2022-07-28 07:37 UTC, qpic-cgi commented on src/main/resources/public/modules/viescolaire/controllers/vsco_grouping_ctrl.ts
> +        return vm.structure.classes.all;
si tu veux, mais il faut quand même faire gaffe que chaque élément est défini par son parent ( structure, puis classes, etc)

2022-07-28 07:38 UTC, qpic-cgi commented on src/main/resources/public/modules/viescolaire/directives/grouping/groupingCreate/grouping-create.html
> +        <button data-ng-click="vm.createGrouping(grouping.name); grouping.name=''">
Comme d'hab, pas fou de chainer les instruction dans ton html comme ça. Privilégie une méthode qui va bien.

2022-07-28 07:39 UTC, qpic-cgi commented on src/main/resources/public/modules/viescolaire/directives/grouping/groupingCreate/grouping-create.ts
> +    createGrouping(nom): void;
the famous "nom"... en anglais pls !
le typage aussi

2022-07-28 07:40 UTC, qpic-cgi commented on src/main/resources/public/modules/viescolaire/directives/grouping/groupingCreate/grouping-create.ts
> +    onCreateGrouping: any;
any ?

2022-07-28 07:40 UTC, qpic-cgi commented on src/main/resources/public/modules/viescolaire/directives/grouping/groupingCreate/grouping-create.ts
> +    $parent: any;
a mon avis => IScope => à tester

2022-07-28 07:41 UTC, qpic-cgi commented on src/main/resources/public/modules/viescolaire/directives/grouping/groupingCreate/grouping-create.ts
> +            console.log("link scope: ", scope);
useless cette méthode non ?

2022-07-28 07:42 UTC, qpic-cgi commented on src/main/resources/public/modules/viescolaire/directives/grouping/groupingItem/grouping-item.html
> +<lightbox show="display.renameGrouping" on-close="display.renameGrouping = false;  groupingTitle='';"
ne chaine pas les instructions

2022-07-28 07:42 UTC, qpic-cgi commented on src/main/resources/public/modules/viescolaire/directives/grouping/groupingItem/grouping-item.html
> +                <button ng-click="vm.updateGroupingItem(vm.groupingItem, groupingTitle); display.renameGrouping = false; groupingTitle='';"
ne chaine pas les instructions

2022-07-28 07:43 UTC, qpic-cgi commented on src/main/resources/public/modules/viescolaire/directives/grouping/groupingItem/grouping-item.html
> +                <button class="cancel right-magnet" ng-click="display.renameGrouping = false; groupingTitle='';">
ne chaine pas les instructions

2022-07-28 07:43 UTC, qpic-cgi commented on src/main/resources/public/modules/viescolaire/directives/grouping/groupingItem/grouping-item.html
> +                        class="right-magnet" disabled="disabled">
tu as un ng-disabled="!groupingTitle" et un disabled="disabled" ?

2022-07-28 07:44 UTC, qpic-cgi commented on src/main/resources/public/modules/viescolaire/directives/grouping/groupingItem/grouping-item.ts
> +    deleteClassItem(groupingClass: GroupingClass, grouping: Grouping, classet: Classe);
classet ?

2022-07-28 07:44 UTC, qpic-cgi commented on src/main/resources/public/modules/viescolaire/directives/grouping/groupingItem/grouping-item.ts
> +    $parent: any;
test IScope

2022-07-28 07:45 UTC, qpic-cgi commented on src/main/resources/public/modules/viescolaire/directives/grouping/groupingItem/grouping-item.ts
> +    onDeleteGroupingAudienceItem: any;
des any par tout, mon dieu...

2022-07-28 07:49 UTC, qpic-cgi commented on src/main/resources/public/modules/viescolaire/directives/grouping/groupingItem/grouping-item.ts
> +        })
pourquoi un foreach ??? 0.0

2022-07-28 07:54 UTC, qpic-cgi commented on src/main/resources/public/modules/viescolaire/directives/grouping/groupingItem/grouping-item.ts
> +        })
tu as vraiment besoin que "classe" soit ne variable global ?

this.groupingClassItem.classes = this.structure.classes.filter(classe => this.groupingItem.class.find(classeItem => classeItem.id === classe.id));
pas mieux ça ?

2022-07-28 07:57 UTC, qpic-cgi commented on src/main/resources/public/modules/viescolaire/directives/grouping/groupingItem/grouping-item.ts
> +            let classeTab = groupingClass.classes.find(classet => classet == classe);
rhoooo, sort moi ça de la boucle !

2022-07-28 07:57 UTC, qpic-cgi commented on src/main/resources/public/modules/viescolaire/directives/grouping/groupingItem/grouping-item.ts
> +            let classeTab = groupingClass.classes.find(classet => classet == classe);
classet ?

2022-07-28 07:59 UTC, qpic-cgi commented on src/main/resources/public/modules/viescolaire/directives/grouping/groupingItem/grouping-item.ts
> +            console.log("link scope: ", scope);
cette fonction est utile ?

2022-07-28 14:43 UTC, qpic-cgi commented on src/main/resources/public/modules/viescolaire/directives/grouping/groupingList/grouping-list.ts
> +    getGroupings(name): void;
type

2022-07-28 14:47 UTC, qpic-cgi commented on src/main/resources/public/modules/viescolaire/directives/grouping/groupingList/grouping-list.ts
> +
bha non

2022-07-28 14:47 UTC, qpic-cgi commented on src/main/resources/public/modules/viescolaire/directives/grouping/groupingList/grouping-list.ts
> +
bha non

2022-07-28 14:47 UTC, qpic-cgi commented on src/main/resources/public/modules/viescolaire/directives/grouping/groupingList/grouping-list.ts
> +
bha non

2022-07-28 14:47 UTC, qpic-cgi commented on src/main/resources/public/modules/viescolaire/directives/grouping/groupingList/grouping-list.ts
> +
bha non

2022-07-28 14:47 UTC, qpic-cgi commented on src/main/resources/public/modules/viescolaire/directives/grouping/groupingList/grouping-list.ts
> +
bha non

2022-07-28 14:47 UTC, qpic-cgi commented on src/main/resources/public/modules/viescolaire/directives/grouping/groupingList/grouping-list.ts
> +
bha non

2022-07-28 15:39 UTC, qpic-cgi commented on src/main/resources/public/modules/viescolaire/controllers/vsco_grouping_ctrl.ts
> +    createGrouping(name: String): Promise<void>;
string

2022-07-28 15:51 UTC, qpic-cgi approved these changes

2022-08-03 13:40 UTC, BastienBenard commented on deployment/viescolaire/conf.json.template
> +           "enable-date" : "2022-09-26"
Juste pour savoir, pourquoi ce changement

2022-08-03 13:48 UTC, BastienBenard commented on src/main/resources/public/modules/viescolaire/directives/grouping/groupingCreate/grouping-create.ts
> +    onCreateGrouping(): void;
Ce n'est pas le bon typage il me semble. onCreateGrouping(): (name: string) => void;

2022-08-03 13:50 UTC, BastienBenard commented on src/main/resources/public/modules/viescolaire/directives/grouping/groupingItem/grouping-item.ts
> +    onDeleteGroupingAudienceItem: () => (scope: IScope, grouping: Grouping, classOrGroup: Classe) => void;
On peut les rajouter dans l'interface IViewModel

2022-08-03 13:52 UTC, BastienBenard commented on src/main/resources/public/modules/viescolaire/directives/grouping/groupingItem/grouping-item.ts
> +            let classeTab = groupingClass.classes.find((classeFind: Classe) => classeFind == classe);
typage

2022-08-03 13:52 UTC, BastienBenard commented on src/main/resources/public/modules/viescolaire/directives/grouping/groupingItem/grouping-item.ts
> +                let classeForAudience = grouping.class.find((classeSelect: Classe) => classeSelect == classe);
typage

2022-08-03 14:04 UTC, BastienBenard commented on src/main/resources/public/sass/global/specifics/_grouping.scss
> +/* View from time slots '/viescolaire/public/templates/viescolaire/param_time_slots.html' */
Est ce que tu peux faire dans petit screen du résultat de ton css

2022-08-03 14:06 UTC, BastienBenard commented on src/main/resources/public/templates/viescolaire/param_etab.html
> +                        <!-- test -->
Cad test ? Si ce commentaire doit réellement rester, est ce que il peut être un peu plus détaillé ?

2022-08-03 14:08 UTC, BastienBenard commented on src/main/resources/public/modules/viescolaire/directives/grouping/groupingCreate/grouping-create.ts
> +    onCreateGrouping(): void;
Et ce que que c'est normal de ne pas l'avoir mis en attribut plutôt que en fonction ?

2022-08-04 10:06 UTC, JinDouang requested changes

2022-08-04 10:06 UTC, JinDouang commented on src/main/resources/public/modules/viescolaire/directives/grouping/groupingItem/grouping-item.ts
> +import {idiom, ng} from "entcore";
à renommer le dossier "grouping-item"

2022-08-04 10:06 UTC, JinDouang commented on src/main/resources/public/modules/viescolaire/directives/grouping/groupingItem/grouping-item.ts
> +import {GroupingService} from "../../../services/GroupingService";
```suggestion
import {GroupingService} from "../../../services";
```

2022-08-04 10:06 UTC, JinDouang commented on src/main/resources/public/modules/viescolaire/directives/grouping/groupingItem/grouping-item.html
> +<div class="grouping-class-list">
Ca manque de commentaire pour le html contenu etc...

2022-08-04 10:06 UTC, JinDouang commented on src/main/resources/public/modules/viescolaire/directives/grouping/groupingCreate/grouping-create.ts
> +import {ng} from "entcore";
à renommer le dossier "grouping-create"

2022-08-04 10:06 UTC, JinDouang commented on src/main/resources/public/modules/viescolaire/directives/grouping/groupingCreate/grouping-create.ts
> +import {GroupingService} from "../../../services/GroupingService";
```suggestion
import {GroupingService} from "../../../services";

```

2022-08-11 19:40 UTC, JinDouang approved these changes

2022-08-17 08:17 UTC, merged