feat(grouping): #MVS-51 create, update and populate grouping is now possible
OPEN-ENT-NG/vie-scolaire pull request #42
Opened 2022-08-09 15:01 UTC by aymericdevriesere

## Describe your changes
Creation of three API:
- Create grouping
- Update grouping
- Populate grouping 
https://confluence.support-ent.fr/display/MTVS/Contrat+d%27API
## Checklist tests
- [x] Create a grouping
- [ ] Update a grouping
- [ ] Populate an existent grouping
- [ ] Populate a non-existent grouping
## Issue ticket number and link
[ MVS-51 ]
https://jira.support-ent.fr/browse/MVS-51
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-08-09 15:19 UTC, BastienBenard commented on src/main/java/fr/openent/viescolaire/helper/PromiseHelper.java
> +        promise.fail(responseAsync.cause());
Est ce que tu peux juste rajouter une condition qui sécurise ? 
```if responseAsync.fail()```

2022-08-09 15:23 UTC, BastienBenard commented on src/main/java/fr/openent/viescolaire/service/ClasseService.java
> +    Future<Boolean> classExist(String classId);
isClassExist

2022-08-09 15:25 UTC, BastienBenard commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultGroupeService.java
> +    protected static final Logger log = LoggerFactory.getLogger(DefaultGroupeService.class);
pourquoi le mettre en protected ?

2022-08-09 15:27 UTC, BastienBenard commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultGroupingService.java
> +    protected static final Logger log = LoggerFactory.getLogger(DefaultGroupingService.class);
Pourquoi protected ?

2022-08-12 07:36 UTC, JinDouang requested changes

2022-08-12 07:36 UTC, JinDouang commented on src/main/java/fr/openent/Viescolaire.java
> +        addController(new GroupingController());
Tu devrais ajouter le serviceFactory dans la classe GroupingController

2022-08-12 07:36 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/controller/GroupingController.java
> +    private final DefaultGroupingService groupingService = new DefaultGroupingService();
Tu devrais ajouter un constructeur avec en param le serviceFactory dans laquelle tu pourrais intégrer DefaultGroupingService

2022-08-12 07:36 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/controller/GroupingController.java
> +    @SecuredAction(value = "", type = ActionType.AUTHENTICATED)
Idem niveau sécurité

2022-08-12 07:36 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/controller/GroupingController.java
> +import io.vertx.core.logging.LoggerFactory;
Pas utilisé tes classes "logging"

2022-08-12 07:36 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/controller/GroupingController.java
> +    @SecuredAction(value = "", type = ActionType.AUTHENTICATED)
Idem niveau sécurité

2022-08-12 07:36 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/core/constants/Field.java
> +    //Test
test ??

2022-08-12 07:36 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultClasseService.java
> +                });
```suggestion
 .onSuccess(res -> promise.complete(res.size() > 0));
```

2022-08-12 07:36 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultClasseService.java
> +        return promise.future();
Pourquoi ne pas gérer le onFailure dessus ?

2022-08-12 07:36 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultGroupeService.java
> +        String query = "MATCH (g:`Group` {id: {groupeId}}) WITH COUNT(g) > 0 as node_exists RETURN node_exists";
je sais pas trop..tu n'as vraiment aucune méthode qui te récupère les infos de groupe ?

Ca serait dommage de faire une requête uniquement pour ton cas qui est très spécifique

2022-08-12 07:36 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultGroupeService.java
> +        values.put("groupeId", groupId);
magic string

2022-08-12 07:36 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultGroupeService.java
> +                promise.complete(((JsonObject)res.right().getValue().getValue(0)).getBoolean("node_exists"));
étrange la vérification..

2022-08-12 07:36 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultGroupingService.java
> +public class DefaultGroupingService implements GroupingService {
Tu n'as pas de constructeur
à revoir la notion d'appel aux autres services

Tu te risques à un import récursive

2022-08-12 07:36 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultGroupingService.java
> +    private DefaultClasseService classeService = new DefaultClasseService();
final

2022-08-12 07:36 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultGroupingService.java
> +        StringBuilder query = new StringBuilder();
Tu n'as pas l'air de solliciter les méthodes du StringBuilder
Tu pourrais le remplacer par un String limite

Genre  String query = "ta requête etc..."

2022-08-12 07:36 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultGroupingService.java
> +        query.append("INSERT INTO viesco.grouping(id, name, structure_id, created_at, updated_at) ")
Pourquoi tu fais des append ? En quoi est-ce nécessaire ?

2022-08-12 07:36 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultGroupingService.java
> +        StringBuilder query = new StringBuilder();
Tu n'as pas l'air de solliciter les méthodes du StringBuilder
Tu pourrais le remplacer par un String limite

Genre String query = "ta requête etc..."

Tu fais que des append...pourquoi pas tout mettre en un coup dans `String` ?

2022-08-12 07:36 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultGroupingService.java
> +                        query.append("INSERT INTO viesco.rel_grouping_class(grouping_id, class_id, group_id, created_at, updated_at) ")
Cette partie là, tu aurais pu l'externaliser en une méthode


Tu pourrais composer tes call promise

2022-08-12 07:36 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultGroupingService.java
> +                    if (res) {
```suggestion
                   Boolean.TRUE.equals(res)
```
https://rules.sonarsource.com/java/RSPEC-5411

2022-08-12 07:36 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultGroupingService.java
> +                        query.append("INSERT INTO viesco.rel_grouping_class(grouping_id, class_id, group_id, created_at, updated_at) ")
Tu comptais une mini test d'intégration pour la grosse méthode ?

2022-08-12 07:36 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultGroupingService.java
> +        ;
???

2022-08-12 07:36 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultGroupingService.java
> +        ;
attention aux indentations

2022-08-12 07:36 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultGroupingService.java
> +                    promise.complete(existence && results.getBoolean(Field.CLASS_EXISTS));
expression lambda
```suggestion
                                 .onSuccess(existence -> promise.complete(existence && results.getBoolean(Field.CLASS_EXISTS)))

```

2022-08-12 07:36 UTC, JinDouang commented on src/main/resources/sql/083-rel-grouping-class.sql
> +    group_id character varying(36) NOT NULL,
Je me trompe peut-être mais du coup si on doit ajouter une relation, il faut obligatoirement avoir un groupe id ET une classe id ?

2022-08-12 09:30 UTC, aymericdevriesere commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultGroupeService.java
> +        String query = "MATCH (g:`Group` {id: {groupeId}}) WITH COUNT(g) > 0 as node_exists RETURN node_exists";
Qui fait ça, non, la seule qui s'en rapproche récupère les classes avec.

2022-08-12 09:33 UTC, aymericdevriesere commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultGroupeService.java
> +                promise.complete(((JsonObject)res.right().getValue().getValue(0)).getBoolean("node_exists"));
Pourquoi ?

2022-08-17 14:30 UTC, flmartineau commented on src/main/java/fr/openent/viescolaire/security/GroupAndClassManage.java
> +    private Future<Boolean> isUserAllowToManageGroupings(UserInfos user, String groupingId) {
Javadoc ? Je trouve le nom de la méthode pas hyper claire.

2022-08-17 14:33 UTC, flmartineau commented on src/main/java/fr/openent/viescolaire/security/GroupAndClassManage.java
> +                String messageToFormat = "[vie-scolaire@%s::isUserAllowToManageGroupings] Error while checking rights : %s";
[Viescolaire@.......] pour être cohérent avec les autres logs

2022-08-17 14:36 UTC, flmartineau commented on src/main/java/fr/openent/viescolaire/security/GroupingRights.java
> +                String messageToFormat = "[vie-scolaire@%s::isUserAllowToManageGroupings] Error while checking rights : %s";
[Viescolaire@%s....]

2022-08-17 14:37 UTC, flmartineau commented on src/main/java/fr/openent/viescolaire/security/GroupingRights.java
> +                .onSuccess(res -> {
` .onSuccess(res -> {
         handler.handle(res && WorkflowActionUtils.hasRight(user, WorkflowActionUtils.ADMIN_RIGHT));
                  
          })`

2022-08-17 14:40 UTC, flmartineau commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultClasseService.java
> +                    String messageToFormat = "[vie-scolaire@%s::isClassExist] Error while checking class existence : %s";
[Viescolaire@%s....]

2022-08-17 14:40 UTC, flmartineau commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultGroupeService.java
> +                promise.complete(((JsonObject)res.right().getValue().getValue(0)).getBoolean("node_exists"));
magic string

2022-08-17 14:41 UTC, flmartineau commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultGroupingService.java
> +            String messageToFormat = "[vie-scolaire@%s::createGrouping] Error while creating grouping : %s";
[Viescolaire...

2022-08-19 05:33 UTC, JinDouang requested changes

2022-08-23 13:52 UTC, BastienBenard commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultGroupingService.java
> +        groupService = (DefaultGroupeService) serviceFactory.groupeService();
Pas besoin de cast

2022-08-23 14:02 UTC, BastienBenard commented on src/test/java/fr/openent/viescolaire/service/impl/DefaultGroupingServiceTest.java
> +@PowerMockRunnerDelegate(VertxUnitRunner.class)
Tu peux l'enlever et remetre @RunWith(VertxUnitRunner.class)

2022-08-23 14:03 UTC, BastienBenard approved these changes

2022-08-24 08:47 UTC, flmartineau commented on src/main/java/fr/openent/viescolaire/security/Grouping/GroupAndClassManage.java
> +                String messageToFormat = "[Viescolaire@%s::isUserAllowToManageGroupings] Error while checking rights : %s";
String messageToFormat = "[Viescolaire@%s::checkGroupingsRights] Error while checking rights : %s";

2022-08-24 08:48 UTC, flmartineau commented on src/main/java/fr/openent/viescolaire/security/Grouping/GroupingRights.java
> +                String messageToFormat = "[Viescolaire@%s::isUserAllowToManageGroupings] Error while checking rights : %s";
pareil

2022-08-24 08:49 UTC, flmartineau commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultGroupeService.java
> +                String messageToFormat = "[Viescolaire@%s::groupExist] Error while checking group existence : %s";
[Viescolaire@%s::isGroupExist]

2022-08-24 08:50 UTC, flmartineau commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultGroupingService.java
> +                String messageToFormat = "[Viescolaire@%s::groupAndClassExist] Error while checking group or class existence : %s";
[Viescolaire@%s::groupOrClassExist]

2022-08-24 09:19 UTC, alicedraillard approved these changes

2022-08-24 09:37 UTC, flmartineau approved these changes

2022-08-24 13:47 UTC, merged