fix(grouping): #MVS-72 fix back API
OPEN-ENT-NG/vie-scolaire pull request #53
Opened 2022-09-06 11:57 UTC by BastienBenard

## Describe your changes
Fix back to answer api doc

Unit tests are currently not passing due to a simulation of successful requests in the service.

Doc: https://confluence.support-ent.fr/display/MTVS/Contrat+d%27API#Contratd'API-addGroupingAudience

## Issue ticket number and link
[MVS-51](https://jira.support-ent.fr/browse/MVS-51)

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [x] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-09-06 14:13 UTC, vava56754 approved these changes

2022-09-06 14:50 UTC, flmartineau commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultGroupeService.java
> +        JsonObject values = new JsonObject().put("idsAudience", new fr.wseduc.webutils.collections.JsonArray(Arrays.asList(idsAudience)));
pas possible de faire new JsonArray ?

2022-09-06 15:21 UTC, JinDouang requested changes

2022-09-06 15:21 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultGroupingService.java
> +                    return jsonArrays.stream()
Pas besoin du return si ce n'est qu'une ligne instruction puis tu peux avoir un lambda expression!

2022-09-06 16:16 UTC, JinDouang requested changes

2022-09-06 16:16 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultGroupeService.java
> +        params.put("idGroupe", new JsonArray(Arrays.asList(idGroupe)))
Si possible gerer le magic string

2022-09-06 16:16 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultGroupingService.java
> +                .map(jsonArrayStudentDivisions -> {
On en reparle mais tu as moyen de simplifier et de skip quelques instructions

2022-09-06 16:16 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultGroupingService.java
> +                            .map(jsonArray -> jsonArray.getString(1))
C'est quoi 1 ?

2022-09-07 09:24 UTC, BastienBenard commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultGroupingService.java
> +                            .map(jsonArray -> jsonArray.getString(1))
```
    [
       {
          "id":"505bcf09-4cb9-4294-8632-29ee5e070f5d",
          "name":"test2",
          "structure_id":"46094e4c-a86f-4b73-812e-890e791a6900",
          "student_divisions":[
             [
                1,
                "df16ac21-7677-4882-8d3d-d142950ba9db" //*1
             ]
          ]
       },
       {
          "id":"48a11c9b-b3b9-42ff-b7be-5572ed190090",
          "name":"test",
          "structure_id":"46094e4c-a86f-4b73-812e-890e791a6900",
          "student_divisions":[
             [
                1,
                "62173c9d-3bb3-44ec-9240-f30ecfb1b4b3"
             ],
             [
                2,
                "6dcc8316-1861-40fa-af52-acc8796ceb7d"
             ]
          ]
       }
    ]
```
Voici un exemple de groupingSQLResults

2022-09-07 13:04 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/service/GroupeService.java
> +    Future<JsonArray> getNameOfGroupeClasse(List<String> idsAudience);
getNameOfGroupClass

2022-09-07 13:12 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultGroupingService.java
> +                        .map(jsonArrayStudentDivision -> jsonArrayStudentDivision.getString(1))
Pourquoi l'index 1 ?

2022-09-07 13:13 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultGroupingService.java
> +                                        .put(Field.ID, ((JsonArray) studentDivision).getString(1))
Pourquoi l'index 1 ?

2022-09-07 13:13 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultGroupingService.java
> +                                        .put(Field.NAME, map.get(((JsonArray) studentDivision).getString(1)))).collect(Collectors.toList());
Pourquoi l'index 1 ?

2022-09-07 13:13 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultGroupingService.java
> +                    Map<String, String> map = jsonArray.stream().map(JsonObject.class::cast)
Il faut revoir le nommage "map" et "jsonArray" en réponse 🤔

2022-09-07 15:33 UTC, JinDouang commented on src/main/resources/sql/082-groupings.sql
>      structure_id character varying(36),
structure_id, mets 255 plutôt

cf (https://github.com/OPEN-ENT-NG/competences/issues/106)

2022-09-08 07:32 UTC, merged