feat(timeslot): #MVS-77 add event bus to get timeslot by student
OPEN-ENT-NG/vie-scolaire pull request #62
Opened 2022-09-27 07:40 UTC by BastienBenard

## Describe your changes

## Checklist tests

## Issue ticket number and link

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-09-27 08:47 UTC, BastienBenard commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultTimeSlotService.java
> -
plus utilisé

2022-09-28 08:38 UTC, JinDouang requested changes

2022-09-28 08:38 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/helper/IModelHelper.java
> +    }
Question de rappel (car je sais pas si on en avait parlé) mais on pouvait pas le mettre dans le modelHelper qu'avait fait @Rseuret ?

2022-09-28 08:38 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/model/SlotModel.java
> +    }
Tous tes getter/setter avant tes autres méthodes

2022-09-28 08:38 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/model/TimeslotModel.java
> +    public TimeslotModel setSlots(List<SlotModel> slots) {
tous tes méthodes getter/slot avant tes autres méthodes

2022-09-28 08:38 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultTimeSlotService.java
> +                            .forEach(relTimeslotClass -> {
lambda

2022-09-28 08:38 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/controller/EventBusController.java
> +                                resultStudentTimeslot.put(student.getId(), timeslotModel.toJson());
lambda

2022-09-28 12:06 UTC, BastienBenard commented on src/main/java/fr/openent/viescolaire/helper/IModelHelper.java
> +    }
On peut, mais je ne pense pas que ce soit une bonne idée, car il y a une différence entre une classe qui extend Model et les classe qui implement IModel

2022-09-28 12:11 UTC, BastienBenard commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultTimeSlotService.java
> +                            .forEach(relTimeslotClass -> {
Je trouve que c'est trop long pour une ligne si on utilise une lambda

2022-09-28 12:12 UTC, BastienBenard commented on src/main/java/fr/openent/viescolaire/controller/EventBusController.java
> +                                resultStudentTimeslot.put(student.getId(), timeslotModel.toJson());
Je trouve que c'est trop long pour une ligne si on utilise une lambda

2022-09-28 17:15 UTC, JinDouang requested changes

2022-09-28 17:15 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/helper/IModelHelper.java
> +    }
Vu avec @BastienBenard pour le mettre dans le ModelHelper

2022-09-29 12:16 UTC, JinDouang approved these changes

2022-09-29 12:17 UTC, merged