feat(services) : MVS-75 Suptopic coefficient are now deleted when suppressing services.
OPEN-ENT-NG/vie-scolaire pull request #63
Opened 2022-09-27 14:46 UTC by FlorentMr

## Describe your changes
Suptopic coefficient are now deleted when suppressing services.

## Checklist tests
Vie Scolaire -> Competences -> Modalité des services -> Delete a service and check in the DB if the subtopics linked to this service are not there.

## Issue ticket number and link
[MVS-75](https://jira.support-ent.fr/browse/MVS-75)

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2022-09-28 08:05 UTC, sjollois approved these changes

2022-09-28 08:05 UTC, sjollois commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultServicesService.java
> +            sql.prepared(query, values, event -> {
C'est voulu de ne plus utiliser Sql.getInstance() ?

2022-09-28 09:34 UTC, JinDouang requested changes

2022-09-28 09:34 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultServicesService.java
> +        }));
Voici ce que je te propose : 

```suggestion
  private Future<JsonObject> deleteSubtopicsOfService(JsonObject oService) {
        Promise<JsonObject> promise = Promise.promise();

        JsonObject action = new JsonObject()
                .put("action", "services.deleteSubtopics")
                .put("id_matiere", oService.getString("id_matiere"))
                .put("id_enseignant", oService.getString("id_enseignant"))
                .put("id_groups", oService.getJsonArray("id_groups"));

        this.eb.request(Viescolaire.COMPETENCES_BUS_ADDRESS, action, handlerToAsyncHandler(event -> {
            if (event.body().getString(Field.STATUS).equals(Field.OK)) {
                promise.complete(new JsonObject().put(Field.RESULTS, event.body().getJsonArray(Field.RESULTS)));
            } else {
                log.error(String.format("[Viescolaire@%s::deleteSubtopicsOfService] Failed to send subtopics infos to delete",
                        this.getClass().getSimpleName()));
                promise.fail(event.body().getString(Field.MESSAGE));
            }
        }));
```

2022-10-07 07:58 UTC, FlorentMr commented on src/main/java/fr/openent/Viescolaire.java
> +        addController(new ServicesController(eb));
Vu avec lui, au final on ne l'a pas fait avec ses changements

2022-10-11 10:17 UTC, JinDouang approved these changes

2022-10-11 10:19 UTC, merged