fix(security): #MVS-96 Add checks on API's routes
OPEN-ENT-NG/vie-scolaire pull request #79
Opened 2023-01-31 15:44 UTC by Gregprod33

## Describe your changes
Add resource filters on routes
## Checklist tests
Checks on ENT and with JVM debugger
## Issue ticket number and link
[#MVS-96](https://jira.support-ent.fr/browse/MVS-96)
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-01-31 16:14 UTC, sjollois approved these changes

2023-02-01 00:49 UTC, JinDouang requested changes

2023-02-01 00:49 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/security/AdministratorRight.java
> +        boolean allowCompetences = WorkflowActionUtils.hasRight(user, WorkflowActions.COMPETENCES_ACCESS.toString());
Est-ce judicieux de dire qu'il faut aussi avoir le droit de workflow `competences access`  pour la sécurité AdministratorRight ?

Sur Normandie par exemple, on peut avoir les outils de la viescolaire sans avoir compétences (cdt, edt...)

Dans ce cas là, on aura tout le temps une 401 puisque le module ne sera jamais déployé

2023-02-01 00:49 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/controller/UserController.java
> +    @ResourceFilter(SuperAdminFilter.class)
Sur les autres APIs où on sécurise avec SuperAdminFilter.class : 
code : https://github.com/opendigitaleducation/entcore/blob/master/common/src/main/java/org/entcore/common/http/filter/SuperAdminFilter.java#L39

Dans ce cas là, on part du principe qu'un utilisateur doit être un SUPER_ADMIN pour utiliser cette route API ? un CPE qui n'aura pas la fonction super admin ne pourra pas utiliser cette API (même s'il a potentiellement les droits côté access/check étab)

2023-02-01 00:49 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/controller/UserController.java
> +    @ResourceFilter(AdministratorRight.class)
Documenter dans le java qu'il est maintenant nécessaire d'avoir une request `structureId`  pour éviter d'avoir une 401 :  

Exemple (à revoir peut-être ?) : 

```
  /**
     * ...
     * @queryParam {structureId} mandatory
     */
  @Delete("/user/structures/actives")
  @ApiDoc("Supprime une structure active pour un module donné.")
  @SecuredAction(value="", type = ActionType.RESOURCE)
  @ResourceFilter(AdministratorRight.class)
```

2023-02-01 08:53 UTC, lapeyronnie commented on src/main/java/fr/openent/viescolaire/controller/UserController.java
>      public void getTeachers(final HttpServerRequest request) {
Pas de resource filter superAdmin ici voir si cette API est utilisé ailleurs

2023-02-01 09:20 UTC, lapeyronnie commented on src/main/java/fr/openent/viescolaire/security/AdministratorRight.java
> +        boolean allowCompetences = WorkflowActionUtils.hasRight(user, WorkflowActions.COMPETENCES_ACCESS.toString());
Cette sécurité est utilisée seulement pour les API de l'onglet compétence de viescolaire et lorsqu'il n'y pas de droit au worflow de parmètrage.

2023-02-01 13:47 UTC, qpic-cgi approved these changes

2023-02-03 09:52 UTC, lapeyronnie approved these changes

2023-02-03 09:53 UTC, merged