MVS-99 accès conseil de classe
OPEN-ENT-NG/vie-scolaire pull request #80
Opened 2023-02-06 10:31 UTC by lapeyronnie

## Describe your changes
fix when a group is not linked at a class
## Checklist tests
avoir un groupe de diffusion contenant des élèves
## Issue ticket number and link
[MVS-99](https://jira.support-ent.fr/browse/MVS-99) lié au ticket [EVAL-471](https://jira.support-ent.fr/browse/EVAL-471)
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-02-06 10:36 UTC, flmartineau commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultPeriodeService.java
> +                                    .format("[Viescolaire@%s::getClasseGroupe] error sql request : %s idGroup : %s.",
[Viescolaire@%s::getPeriodesClasses] plutôt non ?

2023-02-06 10:36 UTC, flmartineau approved these changes

2023-02-06 10:36 UTC, JinDouang approved these changes

2023-02-06 10:37 UTC, aymericdevriesere approved these changes

2023-02-06 10:37 UTC, aymericdevriesere commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultPeriodeService.java
> +                                for(Object o : ((JsonObject) stringJsonArrayEither.right().getValue().iterator().next()).getJsonArray("id_classes")) {
magic string

2023-02-06 10:44 UTC, qpic-cgi requested changes

2023-02-06 10:44 UTC, qpic-cgi commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultPeriodeService.java
> +                                                                    public void handle (Either<String, JsonArray> stringJsonArrayEither) {
à minima, si tu ne veux pas utiliser les promises:
```suggestion
                                                                    getPeriodesGroupe(idEtablissement, idClasses, event -> {
                                                                    ...
                                                                    } 
```

2023-02-06 10:44 UTC, qpic-cgi commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultPeriodeService.java
> +                                                                                groupePeriode.put("id_groupe", idGroupe);
constant

2023-02-06 10:44 UTC, qpic-cgi commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultPeriodeService.java
> +                                for(Object o : ((JsonObject) stringJsonArrayEither.right().getValue().iterator().next()).getJsonArray("id_classes")) {
constant

2023-02-06 10:44 UTC, qpic-cgi commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultPeriodeService.java
> +                                                                            for (Object o : stringJsonArrayEither.right().getValue()) {
```suggestion
                                                                            for (JsonObject groupePeriode : (List<JsonObject>) stringJsonArrayEither.right().getValue().list()) {
```
ça te permet d'avoir une list de jsonbject déjà typé

2023-02-06 10:44 UTC, qpic-cgi commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultPeriodeService.java
> +                                for(Object o : ((JsonObject) stringJsonArrayEither.right().getValue().iterator().next()).getJsonArray("id_classes")) {
```suggestion
                                for(Object o : (List<JsonObject>)((JsonObject) stringJsonArrayEither.right().getValue().iterator().next()).getJsonArray("id_classes").getList()) {
```

2023-02-06 10:54 UTC, lapeyronnie commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultPeriodeService.java
> +                                    .format("[Viescolaire@%s::getClasseGroupe] error sql request : %s idGroup : %s.",
non, c'est le left de la méthode getPeriodesClasses

2023-02-06 12:43 UTC, BastienBenard commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultPeriodeService.java
> +                                            handler.handle(new Either.Right<String, List<String>>(new ArrayList<>(nbPeriodeClasse.keySet())));
```
                                            final Map<String, Integer> idClassPeriodClassNumberMap = stringJsonArrayEither.right().getValue().stream()
                                                    .filter(JsonObject.class::isInstance)
                                                    .map(JsonObject.class::cast)
                                                    .collect(Collectors.groupingBy(periodClass -> periodClass.getString("id_classe")))
                                                    .entrySet()
                                                    .stream()
                                                    .collect(Collectors.toMap(Map.Entry::getKey, stringListEntry -> stringListEntry.getValue().size()));

                                            boolean hasDifferentValues = idClassPeriodClassNumberMap.values().stream().distinct().count() > 1;
                                            if (hasDifferentValues) {
                                                log.error(String
                                                        .format("[Viescolaire@%s::getPeriodesClasses] error : getPeriodesGroupe : Given classes have different type of periods. Classes id: %s",
                                                                this.getClass().getSimpleName(), new JsonArray(new ArrayList<>(idClassPeriodClassNumberMap.keySet()))));
                                                handler.handle(new Either.Left<>("getPeriodesGroupe : Given classes have different type of periods"));
                                            } else {
                                                handler.handle(new Either.Right<>(new ArrayList<>(idClassPeriodClassNumberMap.keySet())));
                                            }
```

2023-02-06 15:28 UTC, qpic-cgi approved these changes

2023-02-07 00:01 UTC, JinDouang approved these changes

2023-02-09 01:03 UTC, JinDouang requested changes

2023-02-09 01:03 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultClasseService.java
> +    }
Avec les commentaires pour les passer en future : 

```suggestion
    public void getEvaluableGroupsClasses(String[] classesIds, Handler<Either<String, JsonArray>> handler) {
        getGroupeClasse(classesIds)
                .onSuccess(classesGroups -> {
                    List<Future<Void>> listFutureGps = new ArrayList<>();
                    if (classesGroups.isEmpty())
                        handler.handle(new Either.Right<>(classesGroups));
                    else {
                        log.info(classesGroups);
                        ((List<JsonObject>) classesGroups.getList()).forEach(classGroupsJo -> {
                            List<String> idsGroups = classGroupsJo.getJsonArray(Field.ID_GROUPES, new JsonArray()).getList();
                            Promise<Void> promiseGroupsClass = Promise.promise();

                            servicesService.getEvaluableGroups(idsGroups)
                                    .onSuccess(event -> {
                                        if (!event.isEmpty()) {
                                            log.info(event);
                                            JsonArray evaluableGroups = new JsonArray();
                                            for (Object evalGroup : event)
                                                evaluableGroups.add(((JsonObject) evalGroup).getString("id_groupe"));
                                            log.info(evaluableGroups);
                                            classGroupsJo.put("id_groupes", evaluableGroups);
                                            log.info(classGroupsJo);
                                        } else {
                                            classesGroups.remove(classGroupsJo);
                                        }
                                        promiseGroupsClass.complete();
                                    })
                                    .onFailure(err -> {
                                        log.error(String.format("[Viescolaire@%s::getEvaluableGroups] error neo request to get evaluable groups : %s",
                                                this.getClass().getSimpleName(), err.getMessage()));
                                        promiseGroupsClass.fail(err.getMessage());
                                    });
                            listFutureGps.add(promiseGroupsClass.future());
                        });
                        FutureHelper.all(listFutureGps)
                                .onSuccess(res -> {
                                    log.info(classesGroups);
                                    handler.handle(new Either.Right<>(classesGroups));
                                })
                                .onFailure(err -> {
                                    log.error(String.format("[Viescolaire@%s::getEvaluableGroups] error get All evaluable groups : %s",
                                            this.getClass().getSimpleName(), err.getMessage()));
                                    handler.handle(new Either.Left<>(err.getMessage()));
                                });
                    }
                })
                .onFailure(err -> {
                    log.error(String.format("[Viescolaire@%s::getEvaluableGroupsClasses] error neo request to get groups of Classes : %s",
                            this.getClass().getSimpleName(), err.getMessage()));
                    handler.handle(new Either.Left<>(err.getMessage()));
                });
    }
```

2023-02-09 13:10 UTC, lapeyronnie commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultPeriodeService.java
> +                                log.error(String.format("[Viecolaire@%s::getPeriodesClasses] error sql resquest : %s",
Je vais mettre les deux comme ça quand aura les logs on sera que c'est cette méthode spécifiquement qui pose problème.

2023-02-09 13:11 UTC, lapeyronnie commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultPeriodeService.java
> +                    log.error(String.format("[Viecolaire@%s::getTypeGroupe] getPeriodes : no class or group found ",
même commentaire que précédemment

2023-02-09 13:29 UTC, lapeyronnie commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultClasseService.java
requête testée sur la Prérod-77, avec la classe 4E de l'établissement camille saint saens voir la demande [EVAL-472](https://jira.support-ent.fr/browse/EVAL-472)

elle retourne seulement les groupes de la structure à laquelle appartient la classe demandée.

2023-02-16 13:18 UTC, closed without merging