fix(security): #MVS-114 add resource filter for API s in TimeSlotController
OPEN-ENT-NG/vie-scolaire pull request #87
Opened 2023-03-09 12:30 UTC by Gregprod33

## Describe your changes

## Checklist tests

## Issue ticket number and link

## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-03-09 13:10 UTC, BastienBenard commented on src/main/java/fr/openent/viescolaire/security/AccessIfMyStructureCheckIdParam.java
> +        String structureId = request.params().get("id");
Magic String

2023-03-09 13:10 UTC, BastienBenard commented on src/main/java/fr/openent/viescolaire/security/AccessIfMyStructureFromAudience.java
> +        final Logger log = LoggerFactory.getLogger(Renders.class);
A placer en variable de classe static

2023-03-09 13:10 UTC, BastienBenard commented on src/main/java/fr/openent/viescolaire/controller/TimeSlotController.java
>      @Put("/time-slots")
A voir pour changé en 
```suggestion
    @Put("/structure/:structureId/time-slots")
```
pour respecter le REST API.
Je pense que tu peux faire cette modification puis que de tout façon tu modifie tout les appels a cause du @queryParam {structureId} mandatory

@lapeyronnie qu'est ce que tu en pense ?

2023-03-09 13:51 UTC, Gregprod33 commented on src/main/java/fr/openent/viescolaire/security/AccessIfMyStructureFromAudience.java
> +        final Logger log = LoggerFactory.getLogger(Renders.class);
corrigé

2023-03-09 13:57 UTC, Gregprod33 commented on src/main/java/fr/openent/viescolaire/controller/TimeSlotController.java
> +     */
Pas de doc API pour cette route

2023-03-10 13:27 UTC, qpic-cgi commented on src/main/java/fr/openent/viescolaire/controller/TimeSlotController.java
>      @Put("/time-slots")
En l'occurrence pour cet endpoint, le body était déjà composé de la structureId avant les modifs.
A voir du coup s'il est judicieux de faire cette modif.

2023-03-10 13:42 UTC, qpic-cgi requested changes

2023-03-10 13:42 UTC, qpic-cgi commented on src/main/java/fr/openent/viescolaire/security/AccessIfMyStructureCheckIdParam.java
> +    }
essai de remplacer tes endpoints par "/structures/:structureId/.../..." (au lieu de "/structures/:id/.../...") comme ça, ça te permet d'utiliser AccessIfMyStructure plutôt, et ça évite de multiplier des checker si ils ont des structure similaires

2023-03-10 13:42 UTC, qpic-cgi commented on src/main/java/fr/openent/viescolaire/security/AccessIfMyStructureFromAudience.java
> +        service.getClasseIdFromAudience(audienceId)
ça fonctionne ça ? tu peux utiliser ton service dans ton ResourcesProvider  ?

2023-03-10 13:42 UTC, qpic-cgi commented on src/main/java/fr/openent/viescolaire/security/AccessIfMyStructureFromAudience.java
> +                    log.error("[Viescolaire@TimeSlotController] Failed to retrieve structure from audience", err.getMessage());
[Viescolaire@AccessIfMyStructureFromAudience::authorize] plutôt

2023-03-13 12:43 UTC, Gregprod33 commented on src/main/java/fr/openent/viescolaire/security/AccessIfMyStructureFromAudience.java
> +                    log.error("[Viescolaire@TimeSlotController] Failed to retrieve structure from audience", err.getMessage());
Fait

2023-03-13 12:43 UTC, Gregprod33 commented on src/main/java/fr/openent/viescolaire/security/AccessIfMyStructureCheckIdParam.java
> +    }
Oui très bien vu, j'ai modifié

2023-03-13 13:07 UTC, flmartineau approved these changes

2023-03-13 13:09 UTC, lapeyronnie commented on src/main/java/fr/openent/viescolaire/controller/TimeSlotController.java
>      @Get("/timeslot/audience/:audienceId")
pour aucun souci, competences ne consomme pas cette API

2023-03-13 13:11 UTC, lapeyronnie approved these changes

2023-03-13 15:35 UTC, merged