Fix(security): #MVS-107 APIs security for EleveController part2
OPEN-ENT-NG/vie-scolaire pull request #93
Opened 2023-03-20 15:23 UTC by Gregprod33

## Describe your changes
Fix security on routes :
@Get("/enseignants")  => Removed because unused
@Get("/eleves") => update neo4j request to remove birthDate from query response and resource filter to check structure.
@Get("/users") => Removed because unused
@Get("/cycle/eleve/:idClasse") => SecuredAction authenticated actually fits well for this route
@Get("/structures/:structureId/students") => Resource filter to check structure.
## Checklist tests

## Issue ticket number and link
[#MVS-107](https://jira.support-ent.fr/browse/MVS-107)
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-03-23 07:25 UTC, lapeyronnie commented
Peux-tu ajouter, stp, les tests à effectuer pour tester la PR.

2023-03-28 07:17 UTC, lapeyronnie commented on src/main/java/fr/openent/viescolaire/service/impl/DefaultEleveService.java
> +                .append(" u.level as level, c.externalId as externalId, ");
ne pas supprimer, la date de naissance l'utilisateur : bécessaire pour le bulletin

2023-03-29 13:24 UTC, lapeyronnie commented on src/main/java/fr/openent/viescolaire/controller/EleveController.java
> +    @ResourceFilter(AccessIfMyStructure.class)
Ne pas changer le ressource filter. Par contre, changer le type d'action RESSOURCE à la place d'AUTHENTICATED

2023-03-29 13:25 UTC, lapeyronnie requested changes
changer type d'action

2023-03-31 07:11 UTC, simonchaval commented on src/main/java/fr/openent/viescolaire/controller/EleveController.java
>      @ResourceFilter(AdminRight.class)
Need to have viescolaire access view to use this API

2023-03-31 07:23 UTC, lapeyronnie approved these changes

2023-03-31 07:26 UTC, merged