fix(security): #MVS-108 add new resourceFilter on route get /groupe/enseignement/users/:groupId in GroupeEnseignementController
OPEN-ENT-NG/vie-scolaire pull request #95
Opened 2023-03-22 10:40 UTC by Gregprod33

## Describe your changes
Create a new resource filter which checks the structure from the groupId in parameter
## Checklist tests

## Issue ticket number and link
[#MVS-108](https://jira.support-ent.fr/browse/MVS-108)
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [ ] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2023-03-22 14:11 UTC, aymericdevriesere approved these changes

2023-03-23 07:13 UTC, JinDouang requested changes

2023-03-23 07:13 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/security/StructureAdminPersonnalTeacherFromGroup.java
> +            if (either.right().getValue() != null && !either.right().getValue().isEmpty()) {
Tu risques d'avoir un NPE si tu check directement l'objet `right`
Pourquoi ne pas faire une vérif classique ? 

`
if (event.isLeft()) {
 // traitement en cas d'erreur
} else {
 // traitement en cas de réussite
}
`

2023-03-23 07:13 UTC, JinDouang commented on src/main/java/fr/openent/viescolaire/security/StructureAdminPersonnalTeacherFromGroup.java
> +public class StructureAdminPersonnalTeacherFromGroup extends DBService implements ResourcesProvider {
Tu n'as pas besoin de DBService

2023-03-23 07:13 UTC, JinDouang commented on src/main/java/fr/openent/Viescolaire.java
> +        DB.getInstance().init(Neo4j.getInstance(), Sql.getInstance(), MongoDb.getInstance());
Tu n'as pas besoin de le déplacer, il y a d'autres alternative (je comprends le besoin qui est d'adapter les TUs mais il y a d'autres alternatives)

2023-03-23 07:23 UTC, lapeyronnie commented
Peux-tu ajouter, stp, les tests à effectuer pour tester la PR.

2023-03-23 15:04 UTC, Gregprod33 commented on src/main/java/fr/openent/viescolaire/security/StructureAdminPersonnalTeacherFromGroup.java
> +            if (either.right().getValue() != null && !either.right().getValue().isEmpty()) {
Méthode changée en Future

2023-03-23 15:04 UTC, Gregprod33 commented on src/main/java/fr/openent/Viescolaire.java
> +        DB.getInstance().init(Neo4j.getInstance(), Sql.getInstance(), MongoDb.getInstance());
Je l'ai remis à sa place

2023-03-23 15:31 UTC, Gregprod33 commented on src/main/java/fr/openent/viescolaire/security/StructureAdminPersonnalTeacherFromGroup.java
> +        Neo4j.getInstance().execute(query ,params, Neo4jResult.validUniqueResultHandler(either -> {
C'est refacto

2023-03-23 17:24 UTC, JinDouang approved these changes

2023-03-24 15:51 UTC, merged